export const Types = {
  newColor:'[Color] Guardado',
  getColor:'[Color] get',
  logeo:'[Auth] inicarLogeo',
  errorLogeo:'[Auth] errorLogeo',
  errorToken:'[token] errorToken',
  estado:'[direccion] obtenerEstado',
  estadoLimpiar:'[direccion] limpiarEstado',
  municipio:'[direccion] obtenerMunicipio',
  municipioLimpiar:'[direccion] limpiarMunicipio',
  proveedorGuardado:'[Proveedor] exito',
  proveedorExiste:'[Proveedor] Existe',
  proveedorLista:'[Proveedor] ObtenerListado',
  limpiarVaribles:'[Variables] Muerte',
  categoriaObtener:'[Categoria] Exito',
  productoGuardar:'[Producto] ExitoGuardado',
  productoError:'[Producto] ErrosGuardas',
  productoLista:'[Producto] ObtenerListado',
  productoUno:'[Producto] ObtenerProducto',
  registroUsuario:'[Usuario] registroUsuarioExito',
  obtenerEmpleados:'[Usuario] sacaEmpleados',
  desactivaUsuario:'[Usuario]',
  activarUsuario:'[Usuario]',
  fracasoregistoUsuario:'[Usuario] registroUsuarioFracaso',
  agregarproductocarrito:'[Carrito] agregaproducto',
  actualizarCarrito:'[Carrito] actualizarcarrito',
  ventaRealizada:'[Venta] ventaRealizada',
  ventasListado:'[Venta] ventaLista',
  limpiarCarrito:'[Carrito] limpiaCarrito',
  limpiarArreglo:'[Lista]'
}